In [2]:
import numpy as np 


THE BASICS 

In [23]:
# One-Dimensional array 
a = np.array([1, 2, 3])

print(a)
print(f'"a" array dimension:" {a.ndim}-D')   
print(f'"a" shape: {a.shape}')
print(f'"a" data type: {a.dtype}')  # dtype is default to int64 on the 64-bit python 

[1 2 3]
"a" array dimension:" 1-D
"a" shape: (3,)
"a" data type: int64


In [24]:
# 2-D array 
b = np.array([[9.,8.,7.], [5., 4., 3.]])

print(b)
print(f'"b" array dimension:" {b.ndim}-D')
print(f'"b" shape: {b.shape}')
print(f'"b" data type: {b.dtype}')  # dtype is default to float64 for float number on the 64-bit python 

[[9. 8. 7.]
 [5. 4. 3.]]
"b" array dimension:" 2-D
"b" shape: (2, 3)
"b" data type: float64


In [7]:
# Specify dtype to int16 
c = np.array([4, 5, 6, 7], dtype='int16')

print(c)
print(f'"c" integer type: {c.dtype}')
print(f'"c" item size: {c.itemsize} bytes')
print(f'"c" takes {c.size * c.itemsize} bytes')
print(f'"c" occupies: {c.nbytes} bytes') # int16 (=2 bytes) * 4 = 8 bytes


[4 5 6 7]
"c" integer type: int16
"c" item size: 2 bytes
"c" takes 8 bytes
"c" occupies: 8 bytes


ACCESSING, CHANGING SPECIFIC ELEMENT, ROWS, COLUMNS 

In [45]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [51]:
# Get specific element by [row, column]. Note: the array is 0-based 
#   for example: get element in the 2nd row, 6th column [1, 5] returns value of 13
print(f'The element of array "a" in [1,5]: {a[1,5]}')
print(f'The element of array "a" in [1,-2]: {a[1,-2]}')  # row 1, the column before the last one

The element of array "a" in [1,5]: 13
The element of array "a" in [1,-2]: 13


In [52]:
# Display all elements of the first row 
print(a[0, :])

[1 2 3 4 5 6 7]


In [53]:
# Display all elements of the 3th column (i.e. column 2)
print(a[:, 2])

[ 3 10]


In [54]:
# Display elements on row from the start of index to end of the index (exclude the element at the end of index with step size [start_index:end_index:step_size])
print(a[0, 1:6:2])

[2 4 6]


In [55]:
# Change the value of a[1,5] to 20
a[1,5]= 20

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [57]:
# Replace all elements in the fourth column (i.e., 3) to value of 5 
a[:, 3] = 5

print(a)

[[ 1  2  3  5  5  6  7]
 [ 8  9 10  5 12 20 14]]


In [58]:
# Replace elements in the fourth column (i.e. 3) to values 1 and 2 respectively
a[:, 3] = [1, 2]

print(a)

[[ 1  2  3  1  5  6  7]
 [ 8  9 10  2 12 20 14]]


In [ ]:
# 3-D Example 

In [4]:
import numpy as np 

b = np.array([[[1,2],[3,4]], [[5,6], [7,8] ]])

print(b.shape)  # can't envision how its 3-D look like 
print(b)

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# Get specific element (working outside in)
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [8]:
# Replace values 
b[:, 1, :] = [[9,9], [8,8]]

print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


INITIALIZE DIFFERENT TYPES OF ARRAYS 

In [9]:
# Initialize 1-D matrix to all (5) 0's 
np.zeros(5)     # use one pair of parentheses for 1-D 

array([0., 0., 0., 0., 0.])

In [11]:
# Initialize 2-D matrix (two rows, 3 columns) to all 0's 
np.zeros((2,3))     # use two pairs of parentheses for 2-D 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# Initialize 3-D matrix (two rows, 3 columns, 3 depths) to all 0's 
np.zeros(((2,3,3)))     # use three pairs of parentheses for 3-D 

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Initialize 3-D matrix (four rows, 2 columns, 2 depths) to all 1's 
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [15]:
# Initialize to other values (99)
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [18]:
# Initialize to other values (4) using full_like method and the existing array structure  
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

print(a)
np.full_like(a, 4)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [19]:
# Fill a 2-D array of four rows, 2 columns with random decimal float value from 0 to 0.99 
np.random.rand(4,2) 

array([[0.17204752, 0.68427251],
       [0.25616489, 0.23743295],
       [0.53601956, 0.5295667 ],
       [0.51283903, 0.27000454]])

In [20]:
# Fill a 2-D array of 3x3 with random integer values of 0 to 6 (excluding 7)
np.random.randint(7, size=(3,3))

array([[2, 3, 5],
       [0, 0, 6],
       [2, 6, 5]])

In [21]:
# Fill a 2-D matrix of 3x3 with random integer values of 4 to 6 (excluding 7)
np.random.randint(4,7, size=(3,3))

array([[4, 4, 6],
       [5, 6, 6],
       [6, 4, 6]])

In [24]:
# Generate an identity 2-D matrix of 5x5 (each row has a walking 1)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# Repeat an array 
a = np.array([1,2,3])

print(a)

# repeat matrix a 3 times 
r1 = np.repeat(a, 3, axis1)

[1 2 3]


NameError: name 'axis1' is not defined

In [40]:
# Generate a 5x5 matrix with all 1's 
output = np.ones((5,5), dtype='int8')
print(output)
print()

# Generate a 3x3 matrix with all 0's
zero_with_9_at_center = np.zeros((3,3), dtype='int8')

# Replace the value of 0 at the center of 3x3 matrix with "9"
zero_with_9_at_center[1,1] = 9
print(zero_with_9_at_center)
print()

# Replace the values at the specified locations in the 5x5 matrix with values from the 3x3 matrix 
output[1:4, 1:4] = zero_with_9_at_center 
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 0 0]
 [0 9 0]
 [0 0 0]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [42]:
# Be caution when copying a matrix. Must be np.copy method 
a = np.array([1,2,3])
b = a.copy()
b[1] = 100 

print(a)
print(b)

[1 2 3]
[  1 100   3]


In [47]:
# If attempt to duplicate a matrix without np.copy() method, it's just a pointer to the same matrix 
print("Before:")
a = np.array([1,2,3])
print(a)
print()

c = a 
c[1] = 100 

print("After:")
print(f'value of matrix c: {c}')
print(f'value of matrix a: {a}')
print("Conclusion: c is just a pointer to matrix a")


Before:
[1 2 3]

After:
value of matrix c: [  1 100   3]
value of matrix a: [  1 100   3]
Conclusion: c is just a pointer to matrix a
