# The Basics 

In [23]:
import numpy as np 

# One-Dimensional array 
a = np.array([1, 2, 3])

print(a)
print(f'"a" array dimension:" {a.ndim}-D')   
print(f'"a" shape: {a.shape}')
print(f'"a" data type: {a.dtype}')  # dtype is default to int64 on the 64-bit python 

[1 2 3]
"a" array dimension:" 1-D
"a" shape: (3,)
"a" data type: int64


In [24]:
# 2-D array 
b = np.array([[9.,8.,7.], [5., 4., 3.]])

print(b)
print(f'"b" array dimension:" {b.ndim}-D')
print(f'"b" shape: {b.shape}')
print(f'"b" data type: {b.dtype}')  # dtype is default to float64 for float number on the 64-bit python 

[[9. 8. 7.]
 [5. 4. 3.]]
"b" array dimension:" 2-D
"b" shape: (2, 3)
"b" data type: float64


In [7]:
# Specify dtype to int16 
c = np.array([4, 5, 6, 7], dtype='int16')

print(c)
print(f'"c" integer type: {c.dtype}')
print(f'"c" item size: {c.itemsize} bytes')
print(f'"c" takes {c.size * c.itemsize} bytes')
print(f'"c" occupies: {c.nbytes} bytes') # int16 (=2 bytes) * 4 = 8 bytes


[4 5 6 7]
"c" integer type: int16
"c" item size: 2 bytes
"c" takes 8 bytes
"c" occupies: 8 bytes


# Accessing, Changing Data on Specific Elements

In [45]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [51]:
# Get specific element by [row, column]. Note: the array is 0-based 
#   for example: get element in the 2nd row, 6th column [1, 5] returns value of 13
print(f'The element of array "a" in [1,5]: {a[1,5]}')
print(f'The element of array "a" in [1,-2]: {a[1,-2]}')  # row 1, the column before the last one

The element of array "a" in [1,5]: 13
The element of array "a" in [1,-2]: 13


In [52]:
# Display all elements of the first row 
print(a[0, :])

[1 2 3 4 5 6 7]


In [53]:
# Display all elements of the 3th column (i.e. column 2)
print(a[:, 2])

[ 3 10]


In [54]:
# Display elements on row from the start of index to end of the index (exclude the element at the end of index with step size [start_index:end_index:step_size])
print(a[0, 1:6:2])

[2 4 6]


In [55]:
# Change the value in a[1,5] to 20
a[1,5]= 20

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [57]:
# Replace all elements in the fourth column to value of 5 
a[:, 3] = 5

print(a)

[[ 1  2  3  5  5  6  7]
 [ 8  9 10  5 12 20 14]]


In [58]:
# Replace elements in the fourth column (i.e. 3) to values 1 and 2 respectively
a[:, 3] = [1, 2]

print(a)

[[ 1  2  3  1  5  6  7]
 [ 8  9 10  2 12 20 14]]


In [ ]:
# 3-D Example 

In [4]:
import numpy as np 

b = np.array([[[1,2],[3,4]], [[5,6], [7,8] ]])

print(b.shape)  # can't envision how its 3-D look like 
print(b)

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# Get specific element (working outside in)
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [8]:
# Replace values 
b[:, 1, :] = [[9,9], [8,8]]

print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initialize Values on Arrays

In [9]:
# Initialize 1-D matrix to all (5) 0's 
np.zeros(5)     # use one pair of parentheses for 1-D 

array([0., 0., 0., 0., 0.])

In [11]:
# Initialize 2-D matrix (two rows, 3 columns) to all 0's 
np.zeros((2,3))     # use two pairs of parentheses for 2-D 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# Initialize 3-D matrix (two rows, 3 columns, 3 depths) to all 0's 
np.zeros(((2,3,3)))     # use three pairs of parentheses for 3-D 

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Initialize 3-D matrix (four rows, 2 columns, 2 depths) to all 1's 
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [15]:
# Initialize to other values (99)
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [18]:
# Initialize to other values (4) using full_like method and the existing array structure  
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

print(a)
np.full_like(a, 4)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [19]:
# Fill a 2-D array of four rows, 2 columns with random decimal float value from 0 to 0.99 
np.random.rand(4,2) 

array([[0.17204752, 0.68427251],
       [0.25616489, 0.23743295],
       [0.53601956, 0.5295667 ],
       [0.51283903, 0.27000454]])

In [20]:
# Fill a 2-D array of 3x3 with random integer values of 0 to 6 (excluding 7)
np.random.randint(7, size=(3,3))

array([[2, 3, 5],
       [0, 0, 6],
       [2, 6, 5]])

In [21]:
# Fill a 2-D matrix of 3x3 with random integer values of 4 to 6 (excluding 7)
np.random.randint(4,7, size=(3,3))

array([[4, 4, 6],
       [5, 6, 6],
       [6, 4, 6]])

In [24]:
# Generate an identity 2-D matrix of 5x5 (each row has a walking 1)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
# Create an array matrix with repeated value 
np.repeat(3, 4)

array([3, 3, 3, 3])

In [71]:
# Repeat an array 
a = np.array([[1,2,3], [4,5,6]])

# Repeat in the matrix 3 times 
np.repeat(a, 3, axis=0)


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [72]:
# Repeat each value 3 times 
a = np.array([[1,2,3], [4,5,6]])
np.repeat(a, 3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

In [40]:
# Generate a 5x5 matrix with all 1's 
output = np.ones((5,5), dtype='int8')
print(output)
print()

# Generate a 3x3 matrix with all 0's
zero_with_9_at_center = np.zeros((3,3), dtype='int8')

# Replace the value of 0 at the center of 3x3 matrix with "9"
zero_with_9_at_center[1,1] = 9
print(zero_with_9_at_center)
print()

# Replace the values at the specified locations in the 5x5 matrix with values from the 3x3 matrix 
output[1:4, 1:4] = zero_with_9_at_center 
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 0 0]
 [0 9 0]
 [0 0 0]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [42]:
# Be caution when copying a matrix. Must be np.copy method 
a = np.array([1,2,3])
b = a.copy()
b[1] = 100 

print(a)
print(b)

[1 2 3]
[  1 100   3]


In [47]:
# If attempt to duplicate a matrix without np.copy() method, it's just a pointer to the same matrix 
print("Before:")
a = np.array([1,2,3])
print(a)
print()

c = a 
c[1] = 100 

print("After:")
print(f'value of matrix c: {c}')
print(f'value of matrix a: {a}')
print("Conclusion: c is just a pointer to matrix a")


Before:
[1 2 3]

After:
value of matrix c: [  1 100   3]
value of matrix a: [  1 100   3]
Conclusion: c is just a pointer to matrix a


# MATHEMATICS:
Note: For more details on all math functions, visit https://docs.scipy.org/doc/numpy/reference/routines.math.html


In [7]:
import numpy as np 

a = np.array([1,2,3, 4])

In [8]:
a + 2

array([3, 4, 5, 6])

In [9]:
a * 2

array([2, 4, 6, 8])

In [10]:
a / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [12]:
a ** 2

array([ 1,  4,  9, 16])

In [11]:
b = np.array([1, 0, 0, 1])

#  adding two arrays 
a + b

array([2, 2, 3, 5])

In [13]:
# sine function 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [14]:
# Cosine function 
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# LINEAR ALGEBRA 
Notes: <ol>
(1) To perform linear algebra on two arrays, the numbers of rows of the first array must be same as the number of columns of the second array
(2) For more details on linear algebra functions, visit https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
</ol>

In [15]:
# Fill 2x3 array a with all 1's
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# Fill 3x2 "b" array with all 2's
b = np.full((3,2), 2)   
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [17]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [18]:
c = np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# Find the determinant 
np.linalg.det(c)

1.0

# Statistics

In [50]:
stats = np.array([[20,2,3,4], [7,5,6,9]])
print(stats)

[[20  2  3  4]
 [ 7  5  6  9]]


## The numpy.m function

In [51]:
# Look for the smallest value in stats 
np.min(stats)

2

In [52]:
# Look for the row having the smaller sum in stats  
np.min(stats, axis=0)

array([7, 2, 3, 4])

In [53]:
# Look for the lowest values in each column
np.min(stats, axis=1)

array([2, 5])

## The numpy.max() function

In [56]:
stats = np.array([[1,2,3,4], [5,6,7,8]])
print(stats)

[[1 2 3 4]
 [5 6 7 8]]


In [42]:
# Look for the biggest value in stats 
np.max(stats)

8

In [57]:
# Look for the row having the highest sum of the values  
np.max(stats, axis=0)

array([5, 6, 7, 8])

In [58]:
# Look for the biggest values in each row
np.max(stats, axis=1)

array([4, 8])

# Reorganizing Arrays

In [61]:
before = np.array([[1,2,3,4], [5,6,7,8]])
before

[[1 2 3 4]
 [5 6 7 8]]


In [65]:
# Reorganize (reshape) the array into 4x2
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Vertical Stacking: Stacking Downward or Vertically

In [66]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
# Vertically stacking vectors 
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

## Horizontal Stacking: Stacking Sideway or Horizontally

In [69]:
h1 = np.ones((2,4))
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [71]:
h2 = np.zeros((2,2))
h2

array([[0., 0.],
       [0., 0.]])

In [73]:
# Peform horizontal stacking
np.hstack([h1,h2,h1])

array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])

# Miscellanous 


In [4]:
# Read text file 
import numpy as np 

fileData = np.genfromtxt("data.txt", delimiter=',')
fileData = fileData.astype("int32")  # configure data to int32

print(fileData)


[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [6]:
# Return data that are greater 50 but less than 100 
fileData[((fileData > 50) & (fileData < 100))]

array([75, 75, 55, 78, 76, 88], dtype=int32)

In [7]:
# Return data that are 50 or less or 100 and more. Note: using the "~" sign for not 
fileData[(~((fileData > 50) & (fileData < 100)))]

array([  1,  13,  21,  11, 196,   4,   3,  34,   6,   7,   8,   0,   1,
         2,   3,   4,   5,   3,  42,  12,  33, 766,   4,   6,   4,   3,
         4,   5,   6,   7,   0,  11,  12,   1,  22,  33,  11, 999,  11,
         2,   1,   0,   1,   2,   9,   8,   7,   1], dtype=int32)

In [13]:
fileData

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [20]:
# Return any COLUMNS having at least one data element that is greater than 50 
np.any(fileData > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [21]:
# Return any ROWS having at least one data element that is greater than 50 
np.any(fileData > 0, axis=1)

array([ True,  True,  True])

In [22]:
# Return only COLUMNS having ALL data elements that are greater than 50 
np.all(fileData > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [23]:
# Return only ROWS having ALL data elements that are greater than 50 
np.all(fileData > 50, axis=1)

array([False, False, False])

In [11]:
a = np.array([1,2,3,4,5,6,7,8,9])

# Index with a list in numpy 
a[[1,2,8]]      # two brackets are needed because the returned value is an array 



array([2, 3, 9])

In [24]:
# Reading the data_matrix text file
fileMatrix = np.genfromtxt("data_matrix.txt", delimiter=',')

fileMatrix = fileMatrix.astype("int32")
fileMatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]], dtype=int32)

In [26]:
# Retrieve data elements having values of 11, 12, 16, and 17
fileMatrix[2:4, 0:2]

array([[11, 12],
       [16, 17]], dtype=int32)

In [28]:
# Retrieve data elements having values of 2, 8, 14, and 20
fileMatrix[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20], dtype=int32)

In [32]:
# Retrieve data elements having values of 24, 25, 29, and 30
fileMatrix[[4,5], 3:]

array([[24, 25],
       [29, 30]], dtype=int32)