In [2]:
import numpy as np 


THE BASICS 

In [23]:
# One-Dimensional array 
a = np.array([1, 2, 3])

print(a)
print(f'"a" array dimension:" {a.ndim}-D')   
print(f'"a" shape: {a.shape}')
print(f'"a" data type: {a.dtype}')  # dtype is default to int64 on the 64-bit python 

[1 2 3]
"a" array dimension:" 1-D
"a" shape: (3,)
"a" data type: int64


In [24]:
# 2-D array 
b = np.array([[9.,8.,7.], [5., 4., 3.]])

print(b)
print(f'"b" array dimension:" {b.ndim}-D')
print(f'"b" shape: {b.shape}')
print(f'"b" data type: {b.dtype}')  # dtype is default to float64 for float number on the 64-bit python 

[[9. 8. 7.]
 [5. 4. 3.]]
"b" array dimension:" 2-D
"b" shape: (2, 3)
"b" data type: float64


In [44]:
# Specify dtype to int16 
c = np.array([4, 5, 6, 7], dtype='int16')

print(c)
print(f'"c" integer type: {c.dtype}')
print(f'"c" number of bytes: {c.nbytes}') # int16 (=2 bytes) * 4 = 8 bytes


[4 5 6 7]
"c" integer type: int16
"c" number of bytes: 8


ACCESSING, CHANGING SPECIFIC ELEMENT, ROWS, COLUMNS 

In [45]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [51]:
# Get specific element by [row, column]. Note: the array is 0-based 
#   for example: get element in the 2nd row, 6th column [1, 5] returns value of 13
print(f'The element of array "a" in [1,5]: {a[1,5]}')
print(f'The element of array "a" in [1,-2]: {a[1,-2]}')  # row 1, the column before the last one

The element of array "a" in [1,5]: 13
The element of array "a" in [1,-2]: 13


In [52]:
# Display all elements of the first row 
print(a[0, :])

[1 2 3 4 5 6 7]


In [53]:
# Display all elements of the 3th column (i.e. column 2)
print(a[:, 2])

[ 3 10]


In [54]:
# Display elements on row from the start of index to end of the index (exclude the element at the end of index with step size [start_index:end_index:step_size])
print(a[0, 1:6:2])

[2 4 6]


In [55]:
# Change the value of a[1,5] to 20
a[1,5]= 20

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [57]:
# Replace all elements in the fourth column (i.e., 3) to value of 5 
a[:, 3] = 5

print(a)

[[ 1  2  3  5  5  6  7]
 [ 8  9 10  5 12 20 14]]


In [58]:
# Replace elements in the fourth column (i.e. 3) to values 1 and 2 respectively
a[:, 3] = [1, 2]

print(a)

[[ 1  2  3  1  5  6  7]
 [ 8  9 10  2 12 20 14]]
